[package]
name = "memory-hashlist"
version = "3.0.0"
description = "Storing and accessing blobs into memory associated with blob-key. (url:https://github.com/fGhost713/Memory-HashList)"
repository = "https://github.com/fGhost713/Memory-HashList"
keywords = [ "memory", "data structures", "storing" ]
license = "MIT"

[dependencies]
base = "0.16.0"
memory-region = "1.3.2"
StableTrieMap = "https://github.com/NatLabs/StableTrieMap#main@4781cb03efd34b124c22396c69710b374366c797"
itertools = "0.2.2"
test = "2.1.1"
vector = "0.4.2"
fuzz = "1.0.0"
bench = "1.0.0"

[toolchain]
wasmtime = "21.0.0"

[dev-dependencies]
bench = "1.0.0"
