name: mops test

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ZenVoich/setup-mops@v1

      - name: Install base package
        run: mops install base@0.16.0

      - name: make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: run tests
        run: mops test
